steps:
    #Decode repo
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          - kms
          - decrypt
          - --ciphertext-file=.env.enc
          - --plaintext-file=.env
          - --location=global
          - --keyring=jointcreative
          - --key=jointcreative

    #Build the jointcreative container
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/$PROJECT_ID', '.']

    #Push joint creative to docker cloud
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/$PROJECT_ID']

    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          - 'run'
          - 'deploy'
          - 'jointcreative'
          - '--image'
          - 'gcr.io/$PROJECT_ID/$PROJECT_ID'
          - '--region'
          - 'us-central1'
          - '--platform'
          - 'managed'
          - '--allow-unauthenticated'
      #Deploy
    - name: 'gcr.io/$PROJECT_ID/firebase'
      args: ['deploy']
